module.exports = {
  FETCH_ALL_PRINTERS: "FETCH_ALL_PRINTERS",
  RECEIVE_ALL_PRINTERS: "RECEIVE_ALL_PRINTERS",

  //Verify List
  FETCH_FILES_TO_VERIFY: "FETCH_FILES_TO_VERIFY",
  RECEIVE_VERIFIED_FILES: "RECEIVE_VERIFIED_FILES",

  // Print cmd
  FETCH_FILES_TO_PRINT: "FETCH_FILES_TO_PRINT",
  RECEIVE_PRINTED_FILES: "RECEIVE_PRINTED_FILES",

  RECEIVE_PRINTED: "RECEIVE_PRINTED",

  //clear
  FETCH_CLEAR: "FETCH_CLEAR",
  RECEIVE_CLEAR: "RECEIVE_CLEAR",
};
